services:
    backend:
        build:
            context: ./docker/backend
            dockerfile: Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./docker/backend
                  target: /app
        container_name: backend
        environment:
            API_URL: http://disasterdata.duckdns.org:5001
            API_KEY: ZIYuaacyfnN4Y17OIqaUMT7YBZWz3M6usplChpoIK3g
            GEOCODE_URL: https://geocode.search.hereapi.com/v1/geocode?q={}&apiKey={}
            CACHE_FILE: location_cache.db
            REDIS_HOST: redis
        volumes:
            - ./config/nltk:/root/nltk_data
        ports:
            - 5000:5000
        restart: unless-stopped
    frontend:
        build:
            context: ./docker/frontend
            dockerfile: Dockerfile
            args:
                REACT_APP_API_HOST: http://localhost/api
        develop:
            watch:
                - action: sync
                  path: ./docker/frontend/react-dashboard/src
                  target: /app/src
                - action: sync
                  path: ./docker/frontend/react-dashboard/public
                  target: /app/public
                - action: rebuild
                  path: ./docker/frontend/react-dashboard/package.json
        container_name: frontend
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        environment:
            DOMAIN: http://localhost
            DUCKDNS_TOKEN: a7b2413a-9f0d-48bf-a3e3-15506deea127
        restart: unless-stopped
        volumes:
            - ./config/caddy/conf:/etc/caddy
            - ./config/caddy/caddy_data:/data
            - ./config/caddy/caddy_config:/config
        depends_on:
            - backend
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
