name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push PostgreSQL image
        run: |
          docker build -t ghcr.io/daot/disasterdata-db:latest ./disasterdata/docker/db
          docker push ghcr.io/daot/disasterdata-db:latest

      - name: Build and push Bsky image
        run: |
          docker build -t ghcr.io/daot/disasterdata-bsky:latest ./disasterdata/docker/bsky
          docker push ghcr.io/daot/disasterdata-bsky:latest

      - name: Build and push Backend image
        run: |
          docker build -t ghcr.io/daot/disasterdata-backend:latest ./disasterdata/docker/backend
          docker push ghcr.io/daot/disasterdata-backend:latest

      - name: Build and push Frontend image
        run: |
          docker build -t ghcr.io/daot/disasterdata-frontend:latest ./disasterdata/docker/frontend
          docker push ghcr.io/daot/disasterdata-frontend:latest

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
